// algorythmo: Stream E — "Sala de Conselho IA" demo dataset.
//
// =========================================================================
// DEMO / REAL-WIRING BOUNDARY
// =========================================================================
// EVERYTHING in this file is illustrative front-end data. It exists so the
// Sala de Conselho runs end-to-end (committee → debate → ghost-line impact
// simulator → approval → work-order checklist) before the OS backend ships.
//
// The real OS layer replaces THIS module — the Vue surfaces consume only the
// shapes defined here, so the wiring drops in without touching components:
//
//   TODO(real-wiring): `DIRECTORS` readiness/freshness comes from the agent
//     runtime (each director-agent reports when it last read OS data).
//   TODO(real-wiring): `INDICATORS[].baseline` is the live macro series
//     pulled from the OS reports layer (Faturamento/Margem/CSAT/load).
//   TODO(real-wiring): `DEBATES[goal]` is generated by the director agents
//     debating each other against real figures — not a canned script.
//   TODO(real-wiring): each proposal's `figure` (data pill) links to a real
//     source report id; `projection` is computed by the simulator engine.
//   TODO(real-wiring): `proposal.workOrder` becomes a real Ordem de Serviço
//     created in the operational tabs on CEO approval.
// =========================================================================

// --- E1 · The Committee -----------------------------------------------------
// Director identities. `seed` pins a stable AlgPlanetAvatar per director.
// `accent` is the SUBTLE per-director colour used as a side-bar/dot in the
// debate flow (NOT a saturated border — the ICE comet stays the system's
// border language; this is a thin semantic tint only).
export const DIRECTORS = [
  {
    id: 'cfo',
    roleKey: 'ALGORYTHMO_ADMIN.C_LEVELS.COMMITTEE.CFO',
    seed: 'algorythmo-cfo-financeiro',
    accent: 'oklch(0.770 0.150 152)', // green — finance
    // TODO(real-wiring): freshness driven by the agent's last data read.
    fresh: true,
    statusKey: 'ALGORYTHMO_ADMIN.C_LEVELS.COMMITTEE.READING',
  },
  {
    id: 'cmo',
    roleKey: 'ALGORYTHMO_ADMIN.C_LEVELS.COMMITTEE.CMO',
    seed: 'algorythmo-cmo-marketing',
    accent: 'oklch(0.700 0.180 015)', // rose — marketing
    fresh: true,
    statusKey: 'ALGORYTHMO_ADMIN.C_LEVELS.COMMITTEE.READING',
  },
  {
    id: 'cto',
    roleKey: 'ALGORYTHMO_ADMIN.C_LEVELS.COMMITTEE.CTO',
    seed: 'algorythmo-cto-tecnologia',
    accent: 'oklch(0.745 0.140 235)', // info blue — tech
    fresh: true,
    statusKey: 'ALGORYTHMO_ADMIN.C_LEVELS.COMMITTEE.READING',
  },
  {
    id: 'coo',
    roleKey: 'ALGORYTHMO_ADMIN.C_LEVELS.COMMITTEE.COO',
    seed: 'algorythmo-coo-operacoes',
    accent: 'oklch(0.780 0.150 075)', // amber — operations
    fresh: true,
    statusKey: 'ALGORYTHMO_ADMIN.C_LEVELS.COMMITTEE.READING',
  },
];

// --- E3 · Impact Simulator indicators ---------------------------------------
// Each indicator carries a 12-point baseline series (the "now"). A proposal's
// projection overrides the tail of the series with a dotted ghost line.
// `unit` and `format` drive the inline SVG axis labels.
//
// TODO(real-wiring): baseline series = live OS macro report. The simulator
// keeps the exact shape { id, labelKey, unit, format, baseline:[…12], goodUp }.
export const INDICATORS = [
  {
    id: 'faturamento',
    labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.SIMULATOR.FATURAMENTO',
    unit: 'R$',
    format: 'currencyK',
    goodUp: true,
    baseline: [182, 188, 191, 187, 195, 198, 201, 204, 206, 209, 211, 214],
  },
  {
    id: 'margem',
    labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.SIMULATOR.MARGEM',
    unit: '%',
    format: 'percent',
    goodUp: true,
    baseline: [
      21.2, 21.0, 21.4, 21.1, 21.6, 21.8, 22.0, 22.1, 22.0, 22.2, 22.3, 22.4,
    ],
  },
  {
    id: 'satisfacao',
    labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.SIMULATOR.SATISFACAO',
    unit: '',
    format: 'csat',
    goodUp: true,
    baseline: [88, 87, 89, 88, 90, 91, 90, 92, 91, 92, 93, 93],
  },
  {
    id: 'sobrecarga',
    labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.SIMULATOR.SOBRECARGA',
    unit: '%',
    format: 'percent',
    goodUp: false, // lower is better — overload should fall
    baseline: [64, 66, 67, 65, 68, 69, 71, 70, 72, 71, 73, 74],
  },
];

// Helper to build a ghost projection: keep the baseline up to `splitAt`, then
// bend toward `endValue` over the remaining points. Returns a 12-point series
// where indices < splitAt mirror the baseline (so the ghost diverges from now).
function project(baseline, splitAt, endValue) {
  const start = baseline[splitAt];
  const span = baseline.length - 1 - splitAt;
  return baseline.map((v, i) => {
    if (i < splitAt) return v;
    const t = span === 0 ? 1 : (i - splitAt) / span;
    // ease-in-out curve so the bend reads natural, not a straight ramp.
    const eased = t < 0.5 ? 2 * t * t : 1 - (-2 * t + 2) ** 2 / 2;
    return +(start + (endValue - start) * eased).toFixed(2);
  });
}

// Build one full projection map (indicatorId → 12-point ghost series) from a
// compact spec of { indicatorId: endValue }. `splitAt` is "now" (point 8 of
// 12 → ~3 months of projected future on the tail).
const SPLIT = 8;
function projectionFrom(spec) {
  const out = {};
  INDICATORS.forEach(ind => {
    if (spec[ind.id] === undefined) return;
    out[ind.id] = project(ind.baseline, SPLIT, spec[ind.id]);
  });
  return out;
}

// --- E2/E4 · Scripted debates per preset goal -------------------------------
// Each debate is an ordered list of turns. A turn with `proposal:true` renders
// the three floating actions and (optionally) a `figure` data pill + a
// `projection` that feeds the ghost simulator. `alt` is the canned alternative
// surfaced by "Pedir alternativa".
//
// TODO(real-wiring): replace the scripted turns with live agent debate.

const DEBATES = {
  'cortar-custos': {
    goalKey: 'ALGORYTHMO_ADMIN.C_LEVELS.GOALS.CUT_COSTS',
    turns: [
      {
        id: 't1',
        director: 'cto',
        textKey: 'ALGORYTHMO_ADMIN.C_LEVELS.DEBATE.CUT.CTO_OPEN',
        figure: {
          labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.PILL.INFRA_CUT',
          reportKey: 'ALGORYTHMO_ADMIN.C_LEVELS.REPORT.INFRA',
        },
        proposal: true,
        projection: projectionFrom({
          faturamento: 214, // unchanged
          margem: 23.6, // +1.2pp net margin
          satisfacao: 93,
          sobrecarga: 68, // lighter infra ops
        }),
        alt: {
          id: 't1-alt',
          director: 'cto',
          textKey: 'ALGORYTHMO_ADMIN.C_LEVELS.DEBATE.CUT.CTO_ALT',
          figure: {
            labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.PILL.INFRA_CUT_SOFT',
            reportKey: 'ALGORYTHMO_ADMIN.C_LEVELS.REPORT.INFRA',
          },
          proposal: true,
          projection: projectionFrom({
            faturamento: 214,
            margem: 23.0,
            satisfacao: 93,
            sobrecarga: 71,
          }),
          workOrderKey: 'ALGORYTHMO_ADMIN.C_LEVELS.WORK_ORDER.INFRA_SOFT',
        },
        workOrderKey: 'ALGORYTHMO_ADMIN.C_LEVELS.WORK_ORDER.INFRA',
      },
      {
        id: 't2',
        director: 'cfo',
        textKey: 'ALGORYTHMO_ADMIN.C_LEVELS.DEBATE.CUT.CFO_VALIDATE',
        figure: {
          labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.PILL.MARGIN_GAIN',
          reportKey: 'ALGORYTHMO_ADMIN.C_LEVELS.REPORT.MARGIN',
        },
      },
    ],
  },

  'reduzir-churn': {
    goalKey: 'ALGORYTHMO_ADMIN.C_LEVELS.GOALS.REDUCE_CHURN',
    turns: [
      {
        id: 'c1',
        director: 'coo',
        textKey: 'ALGORYTHMO_ADMIN.C_LEVELS.DEBATE.CHURN.COO_OPEN',
        figure: {
          labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.PILL.CHURN_RATE',
          reportKey: 'ALGORYTHMO_ADMIN.C_LEVELS.REPORT.RETENTION',
        },
        proposal: true,
        projection: projectionFrom({
          faturamento: 224, // retained revenue compounds
          margem: 22.8,
          satisfacao: 96, // onboarding lift
          sobrecarga: 78, // more support load near-term
        }),
        alt: {
          id: 'c1-alt',
          director: 'coo',
          textKey: 'ALGORYTHMO_ADMIN.C_LEVELS.DEBATE.CHURN.COO_ALT',
          figure: {
            labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.PILL.CHURN_AGENT',
            reportKey: 'ALGORYTHMO_ADMIN.C_LEVELS.REPORT.RETENTION',
          },
          proposal: true,
          projection: projectionFrom({
            faturamento: 222,
            margem: 23.1,
            satisfacao: 95,
            sobrecarga: 70, // agent absorbs the load
          }),
          workOrderKey: 'ALGORYTHMO_ADMIN.C_LEVELS.WORK_ORDER.CHURN_AGENT',
        },
        workOrderKey: 'ALGORYTHMO_ADMIN.C_LEVELS.WORK_ORDER.CHURN',
      },
      {
        id: 'c2',
        director: 'cfo',
        textKey: 'ALGORYTHMO_ADMIN.C_LEVELS.DEBATE.CHURN.CFO_VALIDATE',
        figure: {
          labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.PILL.LTV_GAIN',
          reportKey: 'ALGORYTHMO_ADMIN.C_LEVELS.REPORT.RETENTION',
        },
      },
    ],
  },

  'aumentar-margem': {
    goalKey: 'ALGORYTHMO_ADMIN.C_LEVELS.GOALS.RAISE_MARGIN',
    turns: [
      {
        id: 'm1',
        director: 'cmo',
        textKey: 'ALGORYTHMO_ADMIN.C_LEVELS.DEBATE.MARGIN.CMO_OPEN',
        figure: {
          labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.PILL.PAID_TRAFFIC',
          reportKey: 'ALGORYTHMO_ADMIN.C_LEVELS.REPORT.MARKETING',
        },
        proposal: true,
        projection: projectionFrom({
          faturamento: 236, // sales forecast rises ~3 months out
          margem: 21.4, // dips now (cash out)
          satisfacao: 92,
          sobrecarga: 76,
        }),
        alt: {
          id: 'm1-alt',
          director: 'cmo',
          textKey: 'ALGORYTHMO_ADMIN.C_LEVELS.DEBATE.MARGIN.CMO_ALT',
          figure: {
            labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.PILL.PRICING',
            reportKey: 'ALGORYTHMO_ADMIN.C_LEVELS.REPORT.MARKETING',
          },
          proposal: true,
          projection: projectionFrom({
            faturamento: 220,
            margem: 24.8, // pricing lifts margin directly
            satisfacao: 91,
            sobrecarga: 74,
          }),
          workOrderKey: 'ALGORYTHMO_ADMIN.C_LEVELS.WORK_ORDER.PRICING',
        },
        workOrderKey: 'ALGORYTHMO_ADMIN.C_LEVELS.WORK_ORDER.PAID_TRAFFIC',
      },
      {
        id: 'm2',
        director: 'cfo',
        textKey: 'ALGORYTHMO_ADMIN.C_LEVELS.DEBATE.MARGIN.CFO_CHALLENGE',
        figure: {
          labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.PILL.CASH_DIP',
          reportKey: 'ALGORYTHMO_ADMIN.C_LEVELS.REPORT.MARGIN',
        },
      },
      {
        id: 'm3',
        director: 'cto',
        textKey: 'ALGORYTHMO_ADMIN.C_LEVELS.DEBATE.MARGIN.CTO_SUPPORT',
      },
    ],
  },
};

// Preset goal chips for the opening prompt (E4). Order is intentional.
export const GOALS = [
  {
    id: 'reduzir-churn',
    labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.GOALS.REDUCE_CHURN',
  },
  {
    id: 'cortar-custos',
    labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.GOALS.CUT_COSTS',
  },
  {
    id: 'aumentar-margem',
    labelKey: 'ALGORYTHMO_ADMIN.C_LEVELS.GOALS.RAISE_MARGIN',
  },
];

/**
 * Resolve the scripted debate for a goal id. Returns a deep-ish clone so the
 * surface can mutate per-turn UI state (approved/dismissed/showing-alt)
 * without corrupting the source script.
 *
 * TODO(real-wiring): swap for a call into the director-agent debate engine.
 */
export function debateForGoal(goalId) {
  const debate = DEBATES[goalId];
  if (!debate) return null;
  return {
    goalKey: debate.goalKey,
    turns: debate.turns.map(turn => ({ ...turn })),
  };
}

export { SPLIT as PROJECTION_SPLIT };
